version: '3'

services:

  db:
    image: postgres
    restart: always
    env_file: postgres/.env
#    ports:
#      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
