version: '3.1'

services:

  db:
    image: postgres
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

  pg-admin:
    image: dpage/pgadmin4:latest
    restart: always
    env_file: .env
    ports:
    - "5050:80"
    depends_on:
      - db

volumes:
  data: