version: '3'

services:

  db:
    image: postgres
    restart: always
    env_file: postgres/.env
#    ports:
#      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pg-admin:
    image: dpage/pgadmin4:latest
    restart: always
    env_file: postgres/.env
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
